<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EducationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('education')->delete();
        
        \DB::table('education')->insert(array (
            0 => 
            array (
                'id' => 13,
                'contact_id' => 11755,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-05 17:38:19',
                'campana' => 'FB_UIAgenda',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'nutricion/allan',
                'client_landline' => NULL,
                'client_celphone' => '5514479283',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-05 17:38:19',
                'updated_at' => '2023-06-05 17:38:19',
            ),
            1 => 
            array (
                'id' => 20,
                'contact_id' => 12981,
                'usuario_ocm' => 'tel01am1',
                'usuario_crm' => 'tel01am1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-05 18:34:48',
                'campana' => 'FB_UIAgenda',
                'agent_OCM' => 'tel01am1',
                'agent_intra' => 22,
                'supervisor' => NULL,
                'codification' => 'COTIZACION',
                'client_name' => 'YAMILET NOEMI QUINTERO  ESCAMILLA',
                'client_landline' => '5552851316',
                'client_celphone' => '5552851316',
                'client_modality' => 'ONLINE',
                'client_program' => 'Licenciatura en Ciencias de la Comunicación y Relaciones Públicas en Línea ',
                'client_specialty' => 'Licenciatura en Ciencias de la Comunicación y Relaciones Públicas en Línea ',
                'client_street' => 'CAMINO DE LA SECRETARIA',
                'client_number' => '49',
                'client_delegation' => 'GAM',
                'client_state' => 'México',
                'client_sex' => 'Femenino',
                'client_birth' => '2001-01-13',
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-05 18:34:48',
                'updated_at' => '2023-06-05 18:34:48',
            ),
            2 => 
            array (
                'id' => 21,
                'contact_id' => 2112,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 08:22:48',
                'campana' => 'UIManual',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => NULL,
                'client_landline' => NULL,
                'client_celphone' => '5630363499',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 08:22:48',
                'updated_at' => '2023-06-06 08:22:48',
            ),
            3 => 
            array (
                'id' => 22,
                'contact_id' => 12707,
                'usuario_ocm' => 'tel01ha1',
                'usuario_crm' => 'tel01ha1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:11:37',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ha1',
                'agent_intra' => 12,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'Giovani',
                'client_landline' => NULL,
                'client_celphone' => '5575168770',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:11:37',
                'updated_at' => '2023-06-06 09:11:37',
            ),
            4 => 
            array (
                'id' => 23,
                'contact_id' => 13111,
                'usuario_ocm' => 'tel01ha1',
                'usuario_crm' => 'tel01ha1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:24:53',
                'campana' => 'FB_UIMotor',
                'agent_OCM' => 'tel01ha1',
                'agent_intra' => 12,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'roberta/COMERCIO INTER/ALLAN neg internacionales',
                'client_landline' => NULL,
                'client_celphone' => '5571877219',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:24:53',
                'updated_at' => '2023-06-06 09:24:53',
            ),
            5 => 
            array (
                'id' => 24,
                'contact_id' => 9732,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:33:41',
                'campana' => 'FB_UIIn',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'EDUARDO//fabiola  esperando datos de coti',
                'client_landline' => NULL,
                'client_celphone' => '5523424300',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:33:41',
                'updated_at' => '2023-06-06 09:33:41',
            ),
            6 => 
            array (
                'id' => 25,
                'contact_id' => 13162,
                'usuario_ocm' => 'tel01ha1',
                'usuario_crm' => 'tel01ha1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:41:21',
                'campana' => 'FB_UIMotor',
                'agent_OCM' => 'tel01ha1',
                'agent_intra' => 12,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'liz/allan/whats',
                'client_landline' => NULL,
                'client_celphone' => NULL,
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:41:21',
                'updated_at' => '2023-06-06 09:41:21',
            ),
            7 => 
            array (
                'id' => 26,
                'contact_id' => 2228,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:42:17',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => NULL,
                'client_landline' => NULL,
                'client_celphone' => '5521341295',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:42:17',
                'updated_at' => '2023-06-06 09:42:17',
            ),
            8 => 
            array (
                'id' => 27,
                'contact_id' => 1962,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:49:52',
                'campana' => 'UIManual',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => NULL,
                'client_landline' => NULL,
                'client_celphone' => '5518190906',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:49:52',
                'updated_at' => '2023-06-06 09:49:52',
            ),
            9 => 
            array (
                'id' => 28,
                'contact_id' => 13167,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 09:59:35',
                'campana' => 'FB_UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'mariana //fabiola',
                'client_landline' => NULL,
                'client_celphone' => NULL,
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 09:59:35',
                'updated_at' => '2023-06-06 09:59:35',
            ),
            10 => 
            array (
                'id' => 29,
                'contact_id' => 13173,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 10:43:29',
                'campana' => 'FB_UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'para su esposo //faby',
                'client_landline' => NULL,
                'client_celphone' => '5617748797',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 10:43:29',
                'updated_at' => '2023-06-06 10:43:29',
            ),
            11 => 
            array (
                'id' => 30,
                'contact_id' => 9860,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 10:46:04',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'JOAQUÍN ESCAMILLA PÉREZ FAB//FLEX/ADMON/CHALCO',
                'client_landline' => NULL,
                'client_celphone' => '5618984857',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 10:46:04',
                'updated_at' => '2023-06-06 10:46:04',
            ),
            12 => 
            array (
                'id' => 31,
                'contact_id' => 12326,
                'usuario_ocm' => 'tel01ha1',
                'usuario_crm' => 'tel01ha1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:02:10',
                'campana' => 'UIIn',
                'agent_OCM' => 'tel01ha1',
                'agent_intra' => 12,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'AXEL',
                'client_landline' => NULL,
                'client_celphone' => '2225649175',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:02:10',
                'updated_at' => '2023-06-06 11:02:10',
            ),
            13 => 
            array (
                'id' => 32,
                'contact_id' => 12458,
                'usuario_ocm' => 'tel01ha1',
                'usuario_crm' => 'tel01ha1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:33:58',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ha1',
                'agent_intra' => 12,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'Gustavo*//adrian seguimiento*',
                'client_landline' => NULL,
                'client_celphone' => '5519388749',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:33:58',
                'updated_at' => '2023-06-06 11:33:58',
            ),
            14 => 
            array (
                'id' => 33,
                'contact_id' => 11205,
                'usuario_ocm' => 'tel01vh1',
                'usuario_crm' => 'tel01vh1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:35:48',
                'campana' => 'FB_UIIn',
                'agent_OCM' => 'tel01vh1',
                'agent_intra' => 54,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'MIRIAM',
                'client_landline' => NULL,
                'client_celphone' => '5636567111',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:35:48',
                'updated_at' => '2023-06-06 11:35:48',
            ),
            15 => 
            array (
                'id' => 34,
                'contact_id' => 11205,
                'usuario_ocm' => 'tel01vh1',
                'usuario_crm' => 'tel01vh1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:46:05',
                'campana' => 'FB_UIManual',
                'agent_OCM' => 'tel01vh1',
                'agent_intra' => 54,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'MIRIAM',
                'client_landline' => NULL,
                'client_celphone' => '5636567111',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:46:05',
                'updated_at' => '2023-06-06 11:46:05',
            ),
            16 => 
            array (
                'id' => 35,
                'contact_id' => 13037,
                'usuario_ocm' => 'tel01vh1',
                'usuario_crm' => 'tel01vh1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:50:55',
                'campana' => 'FB_UIMotor',
                'agent_OCM' => 'tel01vh1',
                'agent_intra' => 54,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => NULL,
                'client_landline' => NULL,
                'client_celphone' => '6642251112',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:50:55',
                'updated_at' => '2023-06-06 11:50:55',
            ),
            17 => 
            array (
                'id' => 36,
                'contact_id' => 2210,
                'usuario_ocm' => 'tel01vh1',
                'usuario_crm' => 'tel01vh1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 11:58:57',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01vh1',
                'agent_intra' => 54,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'MARISELA CORTES',
                'client_landline' => NULL,
                'client_celphone' => '5587045063',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 11:58:57',
                'updated_at' => '2023-06-06 11:58:57',
            ),
            18 => 
            array (
                'id' => 37,
                'contact_id' => 2212,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 12:01:24',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'JAZMIN GOMEZ',
                'client_landline' => NULL,
                'client_celphone' => '4776062977',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 12:01:24',
                'updated_at' => '2023-06-06 12:01:24',
            ),
            19 => 
            array (
                'id' => 38,
                'contact_id' => 2275,
                'usuario_ocm' => 'tel01mv1',
                'usuario_crm' => 'tel01mv1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 12:01:39',
                'campana' => 'UIManual',
                'agent_OCM' => 'tel01mv1',
                'agent_intra' => 53,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'FERNAND',
                'client_landline' => NULL,
                'client_celphone' => '5519278961',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 12:01:39',
                'updated_at' => '2023-06-06 12:01:39',
            ),
            20 => 
            array (
                'id' => 39,
                'contact_id' => 4005,
                'usuario_ocm' => 'tel01ml1',
                'usuario_crm' => 'tel01ml1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 12:11:07',
                'campana' => 'UIMotor',
                'agent_OCM' => 'tel01ml1',
                'agent_intra' => 19,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => 'MARIANA FLORES BORGONIO',
                'client_landline' => NULL,
                'client_celphone' => '5574818049',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 12:11:07',
                'updated_at' => '2023-06-06 12:11:07',
            ),
            21 => 
            array (
                'id' => 40,
                'contact_id' => 10403,
                'usuario_ocm' => 'tel01mv1',
                'usuario_crm' => 'tel01mv1',
                'nombre_universidad' => 'UIN',
                'fp_venta' => '2023-06-06 12:16:08',
                'campana' => 'UIManual',
                'agent_OCM' => 'tel01mv1',
                'agent_intra' => 53,
                'supervisor' => NULL,
                'codification' => 'AGENDA',
                'client_name' => NULL,
                'client_landline' => NULL,
                'client_celphone' => '5524060739',
                'client_modality' => NULL,
                'client_program' => NULL,
                'client_specialty' => NULL,
                'client_street' => NULL,
                'client_number' => NULL,
                'client_delegation' => NULL,
                'client_state' => NULL,
                'client_sex' => NULL,
                'client_birth' => NULL,
                'status' => NULL,
                'documents_portal' => NULL,
                'account_UIN' => NULL,
                'created_at' => '2023-06-06 12:16:08',
                'updated_at' => '2023-06-06 12:16:08',
            ),
        ));
        
        
    }
}